### ISSUE TITLE
Incompatibilities new ArduinoJSON library

### ISSUE THREAD

**Issue by Wim3d** [witnessmenow/arduino-ifttt-maker#5]
Hello, thanks for your great work.
After updating to the new ArduinoJSON library I got compiling errors concerning the definition of Dynamicjsonbuffer etc.
I solved my problem by downgrading to a previous version of the ArduinoJSON library

**Comment by flskier** [comment]
Similar issues but tried all versions of ArduinoJSON library. 

Getting errors below:

  "'ArduinoJson::JsonObject' has no member named 'measureLength'
     int length = payload.measureLength();
                          ^
/Documents/Arduino/libraries/IFTTTMaker/src/IFTTTMaker.cpp:82:13: error: 'ArduinoJson::JsonObject' has no member named 'printTo'
     payload.printTo(out);
             ^
Documents/Arduino/libraries/IFTTTMaker/src/IFTTTMaker.cpp: In member function 'bool IFTTTMaker::triggerEvent(String, String, String, String)':
Documents/Arduino/libraries/IFTTTMaker/src/IFTTTMaker.cpp:105:3: error: 'DynamicJsonBuffer' was not declared in this scope
   DynamicJsonBuffer jsonBuffer;

Thanks,
Andy

**Comment by Wim3d** [comment]
For me it works with ArduinoJSON library version 5.13.2

**Comment by flskier** [comment]
Thanks!  That worked.  This is a really useful tool.  I hope that the current/future versions get updated to keep this working.

Thanks,
Andy

**Comment by SCKStef** [comment]
The issue is still open because I use the actual json library to read my config files...
There is a tutorial how to migrate to the new json library on the github page form the author, maybe you could take a look at it :-)

**Comment by witnessmenow** [comment]
This is not even close to being on my radar at the moment, but feel free to
submit a pull request with the changes

**Comment by jellewie** [comment]
I can still confirm the errors occur.

Downgrading to ArduinoJson 5.X works in the meantime
